// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRmHRSIRBUvfzP5i-chHhB1irHbI3CDPw',
    appId: '1:263463511469:android:0218b6f1a58ebf8f692d24',
    messagingSenderId: '263463511469',
    projectId: 'weather-demo-79bdd',
    storageBucket: 'weather-demo-79bdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAnVWega_e8eC_H4T6ThSz7NAJGe6UFvM',
    appId: '1:263463511469:ios:4928cedfb37d1ac5692d24',
    messagingSenderId: '263463511469',
    projectId: 'weather-demo-79bdd',
    storageBucket: 'weather-demo-79bdd.appspot.com',
    iosBundleId: 'com.example.practicalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAnVWega_e8eC_H4T6ThSz7NAJGe6UFvM',
    appId: '1:263463511469:ios:4928cedfb37d1ac5692d24',
    messagingSenderId: '263463511469',
    projectId: 'weather-demo-79bdd',
    storageBucket: 'weather-demo-79bdd.appspot.com',
    iosBundleId: 'com.example.practicalProject',
  );
}
